apiVersion: v1
kind: Service
metadata:
  name: {{ include "decent-exporter.fullname" . }}
  labels:
    {{- include "decent-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.config.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "decent-exporter.selectorLabels" . | nindent 4 }}
